### PR TITLE
Add automatically sizes / check JSON

### LINKED ISSUE #15: Github Action for JSON validation
We should introduce a GitHub-Workflow that check the JSON files in this repo if they are valid when changing files.

See problem here: https://github.com/vcmi/vcmi-mods-repository/pull/14

@IvanSavenko @kambala-decapitator Do any of you know how to do this?

### PR DESCRIPTION
**Pull request by Laserlicht**
See here: https://github.com/Laserlicht/vcmi-mods-repository/commit/21563aaa8c11a9bce05ad8ee0242f2e0381c82f9 (not up to date... changed ": " to " : " in json format)
and here: https://github.com/Laserlicht/vcmi-mods-repository/actions/runs/6208367434

fixes: #15

Also added as check similar to #20 (currently vcmi-1.4 is corrupt again...).

It also automatically formats json by writing sizes.

Runs once a day / after changes of json in this repo. Also detects not existing links to mods. Old JSONs are filtered out currently.

@Nordsoft91 @IvanSavenko This should be a much better approach as adding it to every mod.

After commit following permission has to be set: https://github.com/EndBug/add-and-commit/issues/483

### CODE REVIEW

**Comment by IvanSavenko** [comment]
Thanks again :)

- Can we round to like 3 digits after comma and not this: `"size": 7.284444808959961`?
- ~Why vcmi-1.3 repository is excluded? This is what people actively use right now.~ Ah, that's for downloadSize entry which only exists in 1.4.
- Do we check repository json in strict mode? (no comments allowed)
- Can we also check all referenced mod.json's for syntax validness in strict mode?

**Comment by Laserlicht** [comment]
> Can we round to like 3 digits after comma and not this: `"size": 7.284444808959961`?

Done. ;)

> Do we check repository json in strict mode? (no comments allowed)

Yes - Action is strict
Edit: I'm wrong... Check it also with Python now...

> Can we also check all referenced mod.json's for syntax validness in strict mode?

Done, Python is also strict. :)
https://github.com/Laserlicht/vcmi-mods-repository/actions/runs/6208815716/job/16855368273

**Comment by Laserlicht** [comment]
@IvanSavenko 

Should be okay now.

See here:
https://github.com/Laserlicht/vcmi-mods-repository/actions/runs/6209031677/job/16855807704
and
https://github.com/Laserlicht/vcmi-mods-repository/actions/runs/6208939175

and result with sizes:
https://github.com/Laserlicht/vcmi-mods-repository/blob/b229969a424ebea25dab4aa6a6dab6582fba9b5a/vcmi-1.4.json

**Comment by IvanSavenko** [comment]
Looks OK, merging.
"Workflow permissions" is already set to "Read and write" in this repo

**Comment by IvanSavenko** [comment]
Seems to be working as intended.
Will fix mod.json in mod repositories and try manual re-run.

**Pull request merged**
